@extends('layouts.app')
@section('title', 'Kalender Kegiatan')

@section('content')
    <div class="container-fluid py-4">
        {{-- Header Section --}}
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="card border-0 shadow-sm"
                    style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 15px;">
                    <div class="card-body py-4">
                        <div class="d-flex align-items-center gap-3 text-white">
                            <div
                                style="width: 60px; height: 60px; background: rgba(255,255,255,0.2); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="bi bi-calendar-event" style="font-size: 2rem;"></i>
                            </div>
                            <div>
                                <h2 class="fw-bold mb-1">Kalender Kegiatan</h2>
                                <p class="mb-0 opacity-75">Jadwal dan kegiatan asrama bulan ini</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{-- Calendar Section --}}
        <div class="row g-4">
            <div class="col-lg-8">
                <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                    <div class="card-header bg-white border-bottom py-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="fw-bold mb-0">
                                <i class="bi bi-calendar3 me-2" style="color: #667eea;"></i>
                                <span id="currentMonth">{{ now()->format('F Y') }}</span>
                            </h5>
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-outline-primary btn-sm" id="prevMonth">
                                    <i class="bi bi-chevron-left"></i>
                                </button>
                                <button type="button" class="btn btn-outline-primary btn-sm" id="todayBtn">Hari
                                    Ini</button>
                                <button type="button" class="btn btn-outline-primary btn-sm" id="nextMonth">
                                    <i class="bi bi-chevron-right"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-4">
                        <div id="calendar" class="calendar-grid">
                            {{-- Calendar will be generated by JavaScript --}}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                {{-- Upcoming Events --}}
                <div class="card border-0 shadow-sm mb-4" style="border-radius: 15px;">
                    <div class="card-header"
                        style="background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); color: white; border-radius: 15px 15px 0 0;">
                        <h6 class="fw-bold mb-0"><i class="bi bi-clock-history me-2"></i>Kegiatan Mendatang</h6>
                    </div>
                    <div class="card-body p-3">
                        <div class="event-item mb-3 p-3"
                            style="background: #f8f9fa; border-radius: 10px; border-left: 4px solid #43e97b;">
                            <div class="d-flex align-items-center gap-2 mb-2">
                                <i class="bi bi-calendar-check text-success"></i>
                                <strong class="text-success">Rapat Warga</strong>
                            </div>
                            <small class="text-muted d-block"><i class="bi bi-clock me-1"></i>Minggu, 17 Nov 2024 -
                                14:00</small>
                            <small class="text-muted d-block mt-1">Aula Lantai 1</small>
                        </div>
                        <div class="event-item mb-3 p-3"
                            style="background: #f8f9fa; border-radius: 10px; border-left: 4px solid #667eea;">
                            <div class="d-flex align-items-center gap-2 mb-2">
                                <i class="bi bi-megaphone text-primary"></i>
                                <strong class="text-primary">Lomba Kebersihan</strong>
                            </div>
                            <small class="text-muted d-block"><i class="bi bi-clock me-1"></i>Selasa, 19 Nov 2024 -
                                08:00</small>
                            <small class="text-muted d-block mt-1">Seluruh Kamar</small>
                        </div>
                        <div class="event-item mb-3 p-3"
                            style="background: #f8f9fa; border-radius: 10px; border-left: 4px solid #fa709a;">
                            <div class="d-flex align-items-center gap-2 mb-2">
                                <i class="bi bi-calendar-x text-danger"></i>
                                <strong class="text-danger">Batas Pembayaran</strong>
                            </div>
                            <small class="text-muted d-block"><i class="bi bi-clock me-1"></i>Kamis, 21 Nov 2024</small>
                            <small class="text-muted d-block mt-1">Denda bulan ini</small>
                        </div>
                    </div>
                </div>

                {{-- Legend --}}
                <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                    <div class="card-header bg-white border-bottom py-3">
                        <h6 class="fw-bold mb-0"><i class="bi bi-info-circle me-2" style="color: #667eea;"></i>Keterangan
                        </h6>
                    </div>
                    <div class="card-body">
                        <div class="d-flex align-items-center gap-2 mb-3">
                            <div
                                style="width: 20px; height: 20px; background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); border-radius: 5px;">
                            </div>
                            <span class="small">Kegiatan Asrama</span>
                        </div>
                        <div class="d-flex align-items-center gap-2 mb-3">
                            <div
                                style="width: 20px; height: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 5px;">
                            </div>
                            <span class="small">Lomba/Kompetisi</span>
                        </div>
                        <div class="d-flex align-items-center gap-2 mb-3">
                            <div
                                style="width: 20px; height: 20px; background: linear-gradient(135deg, #fa709a 0%, #fee140 100%); border-radius: 5px;">
                            </div>
                            <span class="small">Batas Waktu</span>
                        </div>
                        <div class="d-flex align-items-center gap-2">
                            <div
                                style="width: 20px; height: 20px; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); border-radius: 5px;">
                            </div>
                            <span class="small">Hari Libur</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .calendar-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 8px;
        }

        .calendar-day-header {
            text-align: center;
            font-weight: bold;
            padding: 10px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 8px;
            font-size: 0.9rem;
        }

        .calendar-day {
            aspect-ratio: 1;
            border: 2px solid #e9ecef;
            border-radius: 10px;
            padding: 8px;
            text-align: center;
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            background: white;
        }

        .calendar-day:hover {
            border-color: #667eea;
            transform: translateY(-3px);
            box-shadow: 0 5px 15px rgba(102, 126, 234, 0.2);
        }

        .calendar-day.today {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            font-weight: bold;
            border-color: #667eea;
        }

        .calendar-day.has-event::after {
            content: '';
            position: absolute;
            bottom: 5px;
            left: 50%;
            transform: translateX(-50%);
            width: 6px;
            height: 6px;
            background: #43e97b;
            border-radius: 50%;
        }

        .calendar-day.other-month {
            opacity: 0.3;
        }

        .calendar-day.weekend {
            background: #f8f9fa;
        }

        .event-item {
            transition: all 0.2s ease;
        }

        .event-item:hover {
            transform: translateX(5px);
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
@endsection

@push('scripts')
    <script>
        let currentDate = new Date();

        function renderCalendar() {
            const year = currentDate.getFullYear();
            const month = currentDate.getMonth();

            // Update month display
            const monthNames = ["Januari", "Februari", "Maret", "April", "Mei", "Juni",
                "Juli", "Agustus", "September", "Oktober", "November", "Desember"
            ];
            $('#currentMonth').text(`${monthNames[month]} ${year}`);

            // Get first day of month and number of days
            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const daysInPrevMonth = new Date(year, month, 0).getDate();

            let html = '';

            // Day headers
            const dayHeaders = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
            dayHeaders.forEach(day => {
                html += `<div class="calendar-day-header">${day}</div>`;
            });

            // Previous month days
            for (let i = firstDay - 1; i >= 0; i--) {
                html += `<div class="calendar-day other-month">${daysInPrevMonth - i}</div>`;
            }

            // Current month days
            const today = new Date();
            for (let day = 1; day <= daysInMonth; day++) {
                const date = new Date(year, month, day);
                const isToday = date.toDateString() === today.toDateString();
                const isWeekend = date.getDay() === 0 || date.getDay() === 6;
                const hasEvent = [17, 19, 21].includes(day); // Sample events

                let classes = 'calendar-day';
                if (isToday) classes += ' today';
                if (isWeekend) classes += ' weekend';
                if (hasEvent) classes += ' has-event';

                html += `<div class="${classes}">${day}</div>`;
            }

            // Next month days
            const remainingDays = 42 - (firstDay + daysInMonth);
            for (let day = 1; day <= remainingDays; day++) {
                html += `<div class="calendar-day other-month">${day}</div>`;
            }

            $('#calendar').html(html);
        }

        $(document).ready(function() {
            renderCalendar();

            $('#prevMonth').click(function() {
                currentDate.setMonth(currentDate.getMonth() - 1);
                renderCalendar();
            });

            $('#nextMonth').click(function() {
                currentDate.setMonth(currentDate.getMonth() + 1);
                renderCalendar();
            });

            $('#todayBtn').click(function() {
                currentDate = new Date();
                renderCalendar();
            });

            // Click on day
            $(document).on('click', '.calendar-day:not(.other-month)', function() {
                $('.calendar-day').removeClass('selected');
                $(this).addClass('selected');
                // You can add functionality to show events for selected day
            });
        });
    </script>
@endpush
